image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- go
sources:
- https://git.sr.ht/~rodolphoeck/emorbita
environment:
  site: em-orbita.com.br
tasks:
- build: |
    cd emorbita
    go build foguete.go
- launch: |
      cd emorbita
      ./foguete
- package: |
    cd emorbita/orbita
    tar -cvz . > ../site.tar.gz
- upload: |
    cd emorbita
    acurl -f https://pages.sr.ht/publish/$site \
        -Fcontent=@site.tar.gz \
        -Fprotocol=GEMINI
