image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
secrets:
- 1b9b349e-1553-46e7-a187-f137d532fba4
sources:
- git@git.sr.ht:~rodolphoeck/emorbita
environment:
  site: em-orbita.com
tasks:
- package: |
    cd emorbita/rodolpho
    tar -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site \
        -Fcontent=@site.tar.gz \
        -Fprotocol=GEMINI
